version: "3.7"
services:
  gw1:
    image: hyc-faspio-team-docker-local.artifactory.swg-devops.com/fasp.io
    ports:
      - "21:2121"
      - "2000:2000"
    # Need to override the docker-entrypoint.sh script that would otherwise overwrite the gateway.toml
    entrypoint: ""
    volumes:
      - ./gateway1.toml:/etc/fasp.io/gateway.toml
  gw2:
    image: hyc-faspio-team-docker-local.artifactory.swg-devops.com/fasp.io
    expose:
      - "2121"
      - "2000"
    # Need to override the docker-entrypoint.sh script that would otherwise overwrite the gateway.toml
    entrypoint: ""
    volumes:
      - ./gateway2.toml:/etc/fasp.io/gateway.toml
  vsftpd:
    image: promiscuous-vsftpd
    build:
      context: ./vsftpd
    volumes:
      - ./logs:/var/log
      - ./data:/home/vsftpd
    restart: always
    expose:
      - "21"
      - "2000"
    environment:
      - FTP_USER=myuser
      - FTP_PASS=mypass
      - PASV_MIN_PORT=2000
      - PASV_MAX_PORT=2000
